# Generated by Django 4.1.1 on 2023-01-23 00:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plataforma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, null=True, unique=True, verbose_name='Plataforma a la cual va dirigida la solicitud:')),
            ],
        ),
        migrations.CreateModel(
            name='TipoUnidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, null=True, unique=True, verbose_name='Tipo de unidad')),
            ],
        ),
        migrations.CreateModel(
            name='Unidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, null=True, verbose_name='Nombre de la unidad')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, null=True, unique=True, verbose_name='Usuario que realiza la solicitud')),
            ],
        ),
        migrations.CreateModel(
            name='ResponsableUnidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('unidades', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='software_caracterizacion.unidades', verbose_name='Nombre de la unidad')),
            ],
        ),
        migrations.CreateModel(
            name='Procesos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_pro', models.CharField(max_length=150, null=True, unique=True, verbose_name='Nombre del proceso ')),
                ('pre_pro', models.CharField(max_length=150, verbose_name='Pregunta base del proceso')),
                ('res_pro', models.CharField(max_length=150, verbose_name='Respuesta base del proceso')),
                ('doc_pro', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='No', max_length=2, verbose_name='¿EL proceso requiere documentos para su solución?')),
                ('rep_pro', models.CharField(max_length=150, verbose_name='Persona responsable del proceso')),
                ('tie_pro', models.CharField(max_length=100, verbose_name='Tiempo en resolver la solicitud del usuario')),
                ('tie_sel', models.CharField(choices=[('Minutos', 'Minutos'), ('Horas', 'Horas'), ('Días', 'Días')], default='Horas', max_length=8, verbose_name='')),
                ('aut_pro', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='No', max_length=2, verbose_name='Automatizar')),
                ('fec_pro', models.CharField(default='2023/01/23', editable=False, max_length=50, verbose_name='Fecha')),
                ('hor_pro', models.CharField(default='00:17:33', editable=False, max_length=50, verbose_name='Hora')),
                ('plataformaid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='software_caracterizacion.plataforma', verbose_name='Plataforma a la cual va dirigida la solicitud:')),
                ('responsableid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='software_caracterizacion.responsableunidad', verbose_name='Responsable de la unidad que recibe la solicitud')),
                ('tipoprocesoid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='software_caracterizacion.tipounidad', verbose_name='Tipo de unidad que recibe la solicitud')),
                ('unidadesid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='software_caracterizacion.unidades', verbose_name='Unidad que recibe la solicitud')),
                ('user', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Procesos', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('usuarioid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='software_caracterizacion.usuario', verbose_name='Usuario que realiza la solicitud')),
            ],
        ),
    ]
