# Generated by Django 4.1 on 2022-09-02 17:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Procesos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idp_pro', models.CharField(max_length=10, unique=True, verbose_name='Identificación')),
                ('nom_pro', models.CharField(max_length=150, null=True, verbose_name='Nombre')),
                ('cli_pro', models.CharField(choices=[('E', 'Estudiante'), ('D', 'Docente')], default='E', max_length=1, verbose_name='Cliente')),
                ('pre_pro', models.CharField(max_length=150, verbose_name='Preguntas')),
                ('res_pro', models.CharField(max_length=150, verbose_name='Respuestas')),
                ('pro_pro', models.CharField(choices=[('Ingenieria de sitemas', 'Ingenieria de sitemas'), ('Psicologia', 'Psicologia'), ('administración de empresas', 'administración de empresas'), ('arquitectura', 'arquitectura'), ('contaduría pública', 'contaduría pública'), ('departamento de ciencias basicas', 'departamento de ciencias basicas'), ('departamento de ciencias humanas y espiritualidad', 'departamento de ciencias humanas y espiritualidad'), ('deporte universitario', 'deporte universitario'), ('derecho', 'derecho'), ('diseño gráfico', 'diseño gráfico'), ('especialización en arquitectura y urbanismo bioclimático', 'especialización en arquitectura y urbanismo bioclimático'), ('especialización en derecho empresarial', 'especialización en derecho empresarial'), ('especialización en gerencia de proyectos', 'especialización en gerencia de proyectos'), ('especialización en infancia, cultura y desarrollo', 'especialización en infancia, cultura y desarrollo'), ('especialización en pedagogía del entrenamiento deportivo', 'especialización en pedagogía del entrenamiento deportivo'), ('ingeniería de sistemas', 'ingeniería de sistemas'), ('ingeniería electrónica', 'ingeniería electrónica'), ('licenciatura en educacion fisica', 'licenciatura en educacion fisica'), ('licenciatura en educación infantil', 'licenciatura en educación infantil'), ('licenciatura en quimica', 'licenciatura en quimica'), ('profesionalización en administración de empresas', 'profesionalización en administración de empresas'), ('profesionalización en contaduría pública', 'profesionalización en contaduría pública'), ('psicología', 'psicología'), ('tecnología en contabilidad y finanzas', 'tecnología en contabilidad y finanzas'), ('tecnología en gestión financiera', 'tecnología en gestión financiera')], default='Ingenieria de sitemas', max_length=100, verbose_name='Programas')),
                ('pla_pro', models.CharField(choices=[('Ruah', 'Ruah'), ('TAU', 'TAU')], default='Ruha', max_length=100, verbose_name='Plataforma')),
                ('tip_pro', models.CharField(choices=[('Renovacion', 'Renovacion'), ('Cambio contraseña', 'Cambio contraseña'), ('Recuperar correo', 'Recuperar correo')], default='Renovacion', max_length=100, verbose_name='Tipo proceso')),
                ('doc_pro', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='No', max_length=2, verbose_name='Documentos')),
                ('rep_pro', models.CharField(max_length=150, verbose_name='Responsable')),
                ('tie_pro', models.CharField(choices=[('1-4 horas', '1-4 horas'), ('4-8 horas', '4-8 horas'), ('8-12 horas', '8-12 horas'), ('12-16 horas', '12-16 horas'), ('16-20 horas', '16-20 horas'), ('20-24 horas', '20-24 horas'), ('Mas de un día', 'Mas de un día')], default='1-4 horas', max_length=100, verbose_name='Tiempo de respuesta del proceso')),
                ('aut_pro', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='No', max_length=2, verbose_name='Automatizar')),
                ('fec_pro', models.CharField(default='2022/09/02', editable=False, max_length=50, verbose_name='Fecha')),
                ('hor_pro', models.CharField(default='12:05:16', editable=False, max_length=50, verbose_name='Hora')),
                ('user', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Procesos', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
        ),
    ]
