# Generated by Django 4.1.1 on 2022-09-13 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('software_caracterizacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, null=True, verbose_name='Nombre del programa')),
            ],
        ),
        migrations.CreateModel(
            name='TipoProceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, null=True, verbose_name='Tipo proceso')),
            ],
        ),
        migrations.RemoveField(
            model_name='procesos',
            name='idp_pro',
        ),
        migrations.RemoveField(
            model_name='procesos',
            name='pro_pro',
        ),
        migrations.RemoveField(
            model_name='procesos',
            name='tip_pro',
        ),
        migrations.AlterField(
            model_name='procesos',
            name='fec_pro',
            field=models.CharField(default='2022/09/13', editable=False, max_length=50, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='procesos',
            name='hor_pro',
            field=models.CharField(default='14:31:28', editable=False, max_length=50, verbose_name='Hora'),
        ),
        migrations.CreateModel(
            name='Responsable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('programa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='software_caracterizacion.programa', verbose_name='Nombre del programa')),
            ],
        ),
        migrations.AddField(
            model_name='procesos',
            name='programaid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='software_caracterizacion.programa', verbose_name='Nombre del programa'),
        ),
        migrations.AddField(
            model_name='procesos',
            name='responsableid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='software_caracterizacion.responsable', verbose_name='Responsbale'),
        ),
        migrations.AddField(
            model_name='procesos',
            name='tipoprocesoid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='software_caracterizacion.tipoproceso', verbose_name='Tipo proceso'),
        ),
    ]
