# Generated by Django 4.1.1 on 2023-01-23 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software_caracterizacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procesos',
            name='hor_pro',
            field=models.CharField(default='00:22:19', editable=False, max_length=50, verbose_name='Hora'),
        ),
    ]
