# Generated by Django 4.1.1 on 2023-01-23 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software_caracterizacion', '0002_alter_procesos_hor_pro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procesos',
            name='hor_pro',
            field=models.CharField(default='01:16:36', editable=False, max_length=50, verbose_name='Hora'),
        ),
    ]
