# Generated by Django 4.1.1 on 2022-09-13 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software_caracterizacion', '0002_programa_tipoproceso_remove_procesos_idp_pro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procesos',
            name='hor_pro',
            field=models.CharField(default='14:36:39', editable=False, max_length=50, verbose_name='Hora'),
        ),
        migrations.AlterField(
            model_name='tipoproceso',
            name='nombre',
            field=models.CharField(max_length=150, null=True, unique=True, verbose_name='Tipo proceso'),
        ),
    ]
