# Generated by Django 4.1.1 on 2022-09-13 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software_caracterizacion', '0003_alter_procesos_hor_pro_alter_tipoproceso_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procesos',
            name='hor_pro',
            field=models.CharField(default='15:09:47', editable=False, max_length=50, verbose_name='Hora'),
        ),
    ]
