# Generated by Django 4.1.1 on 2022-09-13 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software_caracterizacion', '0004_alter_procesos_hor_pro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procesos',
            name='hor_pro',
            field=models.CharField(default='15:16:35', editable=False, max_length=50, verbose_name='Hora'),
        ),
        migrations.AlterField(
            model_name='procesos',
            name='nom_pro',
            field=models.CharField(max_length=150, null=True, unique=True, verbose_name='Nombre'),
        ),
    ]
