# Generated by Django 4.1.1 on 2022-09-13 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software_caracterizacion', '0005_alter_procesos_hor_pro_alter_procesos_nom_pro'),
    ]

    operations = [
        migrations.AddField(
            model_name='procesos',
            name='tie_sel',
            field=models.CharField(choices=[('E', 'Estudiante'), ('D', 'Docente')], default='Horas', max_length=5),
        ),
        migrations.AlterField(
            model_name='procesos',
            name='cli_pro',
            field=models.CharField(choices=[('E', 'Estudiante'), ('D', 'Docente')], default='E', max_length=1, verbose_name='Usuario que realiza la petición'),
        ),
        migrations.AlterField(
            model_name='procesos',
            name='doc_pro',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='No', max_length=2, verbose_name='¿EL proceso requiere documentos para su solución?'),
        ),
        migrations.AlterField(
            model_name='procesos',
            name='hor_pro',
            field=models.CharField(default='16:33:21', editable=False, max_length=50, verbose_name='Hora'),
        ),
        migrations.AlterField(
            model_name='procesos',
            name='nom_pro',
            field=models.CharField(max_length=150, null=True, unique=True, verbose_name='Digite un nombre al proceso '),
        ),
        migrations.AlterField(
            model_name='procesos',
            name='pla_pro',
            field=models.CharField(choices=[('Ruah', 'Ruah'), ('TAU', 'TAU')], default='Ruha', max_length=100, verbose_name='Plataforma a la cual va dirigida la petición'),
        ),
        migrations.AlterField(
            model_name='procesos',
            name='pre_pro',
            field=models.CharField(max_length=150, verbose_name='Pregunta base del proceso'),
        ),
        migrations.AlterField(
            model_name='procesos',
            name='res_pro',
            field=models.CharField(max_length=150, verbose_name='Respuesta base del proceso'),
        ),
        migrations.AlterField(
            model_name='procesos',
            name='tie_pro',
            field=models.CharField(max_length=100, verbose_name='Tiempo en resolver la petición'),
        ),
    ]
