# Generated by Django 4.1.1 on 2022-09-13 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software_caracterizacion', '0006_procesos_tie_sel_alter_procesos_cli_pro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procesos',
            name='hor_pro',
            field=models.CharField(default='17:01:33', editable=False, max_length=50, verbose_name='Hora'),
        ),
        migrations.AlterField(
            model_name='procesos',
            name='tie_sel',
            field=models.CharField(choices=[('Horas', 'Horas'), ('Días', 'Días')], default='Horas', max_length=5, verbose_name=''),
        ),
    ]
