# Generated by Django 4.1.1 on 2022-09-13 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software_caracterizacion', '0007_alter_procesos_hor_pro_alter_procesos_tie_sel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procesos',
            name='hor_pro',
            field=models.CharField(default='17:08:45', editable=False, max_length=50, verbose_name='Hora'),
        ),
    ]
