# Generated by Django 4.1.1 on 2022-09-13 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software_caracterizacion', '0008_alter_procesos_hor_pro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procesos',
            name='hor_pro',
            field=models.CharField(default='17:10:44', editable=False, max_length=50, verbose_name='Hora'),
        ),
    ]
