# Generated by Django 4.1.1 on 2022-09-13 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('software_caracterizacion', '0009_alter_procesos_hor_pro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plataforma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, null=True, unique=True, verbose_name='Plataforma a la cual va dirigida la petición:')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, null=True, unique=True, verbose_name='Usuario que realiza la petición')),
            ],
        ),
        migrations.AlterField(
            model_name='procesos',
            name='hor_pro',
            field=models.CharField(default='17:23:02', editable=False, max_length=50, verbose_name='Hora'),
        ),
        migrations.AddField(
            model_name='procesos',
            name='plataformaid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='software_caracterizacion.plataforma', verbose_name='Plataforma'),
        ),
        migrations.AddField(
            model_name='procesos',
            name='usuarioid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='software_caracterizacion.usuario', verbose_name='Usuario'),
        ),
    ]
