# Generated by Django 4.1.1 on 2022-09-13 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software_caracterizacion', '0010_plataforma_usuario_alter_procesos_hor_pro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procesos',
            name='hor_pro',
            field=models.CharField(default='17:23:11', editable=False, max_length=50, verbose_name='Hora'),
        ),
    ]
