# Generated by Django 4.1.1 on 2022-09-13 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software_caracterizacion', '0011_alter_procesos_hor_pro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='procesos',
            name='cli_pro',
        ),
        migrations.RemoveField(
            model_name='procesos',
            name='pla_pro',
        ),
        migrations.AlterField(
            model_name='procesos',
            name='hor_pro',
            field=models.CharField(default='17:24:30', editable=False, max_length=50, verbose_name='Hora'),
        ),
    ]
