# Generated by Django 4.1 on 2022-09-13 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('software_caracterizacion', '0012_remove_procesos_cli_pro_remove_procesos_pla_pro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procesos',
            name='hor_pro',
            field=models.CharField(default='14:59:14', editable=False, max_length=50, verbose_name='Hora'),
        ),
        migrations.AlterField(
            model_name='procesos',
            name='nom_pro',
            field=models.CharField(max_length=150, null=True, unique=True, verbose_name='Nombre del proceso '),
        ),
        migrations.AlterField(
            model_name='procesos',
            name='plataformaid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='software_caracterizacion.plataforma', verbose_name='Plataforma a la cual va dirigida la petición:'),
        ),
        migrations.AlterField(
            model_name='procesos',
            name='programaid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='software_caracterizacion.programa', verbose_name='Dependencia (pregiuntar)'),
        ),
        migrations.AlterField(
            model_name='procesos',
            name='responsableid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='software_caracterizacion.responsable', verbose_name='Responsbale (preguntar)'),
        ),
        migrations.AlterField(
            model_name='procesos',
            name='usuarioid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='software_caracterizacion.usuario', verbose_name='Usuario que realiza la petición'),
        ),
        migrations.AlterField(
            model_name='tipoproceso',
            name='nombre',
            field=models.CharField(max_length=150, null=True, unique=True, verbose_name='Tipo de unidad'),
        ),
    ]
