# Generated by Django 4.1.1 on 2022-09-14 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('software_caracterizacion', '0013_alter_procesos_hor_pro_alter_procesos_nom_pro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procesos',
            name='fec_pro',
            field=models.CharField(default='2022/09/14', editable=False, max_length=50, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='procesos',
            name='hor_pro',
            field=models.CharField(default='01:46:57', editable=False, max_length=50, verbose_name='Hora'),
        ),
        migrations.AlterField(
            model_name='procesos',
            name='tipoprocesoid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='software_caracterizacion.tipoproceso', verbose_name='Tipo de unidad'),
        ),
    ]
