# Generated by Django 4.1.1 on 2022-09-15 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('software_caracterizacion', '0016_alter_procesos_hor_pro_alter_procesos_tipoprocesoid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, null=True, verbose_name='Nombre de la Unidad')),
            ],
        ),
        migrations.RemoveField(
            model_name='procesos',
            name='programaid',
        ),
        migrations.RemoveField(
            model_name='responsable',
            name='programa',
        ),
        migrations.AlterField(
            model_name='procesos',
            name='fec_pro',
            field=models.CharField(default='2022/09/15', editable=False, max_length=50, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='procesos',
            name='hor_pro',
            field=models.CharField(default='16:17:28', editable=False, max_length=50, verbose_name='Hora'),
        ),
        migrations.AlterField(
            model_name='procesos',
            name='rep_pro',
            field=models.CharField(max_length=150, verbose_name='Persona responsable del proceso'),
        ),
        migrations.AlterField(
            model_name='procesos',
            name='responsableid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='software_caracterizacion.responsable', verbose_name='Responsbale de la unidad'),
        ),
        migrations.AlterField(
            model_name='procesos',
            name='tie_pro',
            field=models.CharField(max_length=100, verbose_name='Tiempo en resolver la petición del usuario'),
        ),
        migrations.AlterField(
            model_name='procesos',
            name='tipoprocesoid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='software_caracterizacion.tipoproceso', verbose_name='Tipo de unidad'),
        ),
        migrations.DeleteModel(
            name='Programa',
        ),
        migrations.AddField(
            model_name='procesos',
            name='unidadid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='software_caracterizacion.unidad', verbose_name='Unidad'),
        ),
        migrations.AddField(
            model_name='responsable',
            name='unidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='software_caracterizacion.unidad', verbose_name='Nombre del programa'),
        ),
    ]
