# Generated by Django 4.1.1 on 2022-09-15 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('software_caracterizacion', '0017_unidad_remove_procesos_programaid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, null=True, verbose_name='Nombre del programa')),
            ],
        ),
        migrations.RemoveField(
            model_name='procesos',
            name='unidadid',
        ),
        migrations.RemoveField(
            model_name='responsable',
            name='unidad',
        ),
        migrations.AlterField(
            model_name='procesos',
            name='hor_pro',
            field=models.CharField(default='16:25:36', editable=False, max_length=50, verbose_name='Hora'),
        ),
        migrations.DeleteModel(
            name='Unidad',
        ),
        migrations.AddField(
            model_name='procesos',
            name='programaid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='software_caracterizacion.programa', verbose_name='Unidad'),
        ),
        migrations.AddField(
            model_name='responsable',
            name='programa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='software_caracterizacion.programa', verbose_name='Nombre del programa'),
        ),
    ]
