# Generated by Django 4.1.1 on 2022-09-15 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('software_caracterizacion', '0018_programa_remove_procesos_unidadid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, null=True, verbose_name='Nombre de la unidad')),
            ],
        ),
        migrations.RemoveField(
            model_name='procesos',
            name='programaid',
        ),
        migrations.RemoveField(
            model_name='responsable',
            name='programa',
        ),
        migrations.AlterField(
            model_name='procesos',
            name='hor_pro',
            field=models.CharField(default='16:34:30', editable=False, max_length=50, verbose_name='Hora'),
        ),
        migrations.DeleteModel(
            name='Programa',
        ),
        migrations.AddField(
            model_name='procesos',
            name='unidadesid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='software_caracterizacion.unidades', verbose_name='Unidad'),
        ),
        migrations.AddField(
            model_name='responsable',
            name='unidades',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='software_caracterizacion.unidades', verbose_name='Nombre de la unidad'),
        ),
    ]
