# Generated by Django 4.1.1 on 2022-09-15 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software_caracterizacion', '0019_unidades_remove_procesos_programaid_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Responsable',
            new_name='Responsableunidad',
        ),
        migrations.AlterField(
            model_name='procesos',
            name='hor_pro',
            field=models.CharField(default='16:44:06', editable=False, max_length=50, verbose_name='Hora'),
        ),
    ]
