# Generated by Django 4.1 on 2022-09-23 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software_caracterizacion', '0021_alter_plataforma_nombre_alter_procesos_fec_pro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procesos',
            name='hor_pro',
            field=models.CharField(default='10:08:06', editable=False, max_length=50, verbose_name='Hora'),
        ),
    ]
